project_name: storj

before:
  hooks:
    - go mod download

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc

checksum:
  name_template: 'checksums.txt'

builds:
  - env:
      - CGO_ENABLED=1

  - id: multinode
    main: ./cmd/multinode
    binary: multinode

archives:
  - format: zip
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
