name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go mod download
        go build -v ./...
        
    - name: Test
      run: go test -v -p 16 -bench XYZXYZXYZXYZ -run XYZXYZXYZXYZ ./...
    
  build-test-race:
    runs-on: ubuntu-latest
    steps:
        
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go mod download
        go build -v -race ./...
        
    - name: Test
      run: go test -v -p 16 -bench XYZXYZXYZXYZ -run XYZXYZXYZXYZ ./...
