name: Tooling-General_Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  standard-lint:
    runs-on: ubuntu-latest
    steps:
        
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Super-Linter
      uses: github/super-linter@v4.8.5

