name: Tooling-General_Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  standard-lint:
    runs-on: ubuntu-latest
    steps:
        
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
   ################################
   # Run Linter against code base #
   ################################
    - name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        # VALIDATE_ALL_CODEBASE: false
        VALIDATE_TYPESCRIPT_STANDARD: false
        VALIDATE_TYPESCRIPT_ES: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

